E-Learning.PL/Areas/Dashboard/Controllers/TeachersController.cs
using AutoMapper;
using E_Learning.DAL.Data;
using E_Learning.DAL.Models;
using E_Learning.PL.Areas.Dashboard.ViewModels;
using E_Learning.PL.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace E_Learning.PL.Areas.Dashboard.Controllers
{
    [Authorize(Roles = "Admin,superAdmin")]
    [Area("Dashboard")]
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public TeachersController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var teachers = context.Teachers.ToList();
            var showTeachersVM = mapper.Map<IEnumerable<ShowTeachersVM>>(teachers);
            return View(showTeachersVM);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TeacherFormVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            viewModel.ImageName = FilesSettings.UploadFile(viewModel.Image, "images");

            var teacher = mapper.Map<Teacher>(viewModel);
            context.Add(teacher);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

         [HttpGet]
        public IActionResult Details(int id)
        {
            var teacher = context.Teachers.Find(id);
            if (teacher is null)
            {
                return NotFound();
            }

            var teacherM = mapper.Map<TeacherDetailsVM>(teacher);
            return View(teacherM);
        }

        public IActionResult Edit(int id)
        {
            var teacher = context.Teachers.Find(id);
            if (teacher is null)
            {
                return NotFound();
            }

            var teacherM = mapper.Map<TeacherFormVM>(teacher);
            return View(teacherM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Edit(TeacherFormVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var teacher = context.Teachers.Find(viewModel.Id);
            if (teacher is null)
            {
                return NotFound();
            }
            viewModel.ImageName = FilesSettings.UploadFile(viewModel.Image, "images");
            var teacherM = mapper.Map(viewModel, teacher);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public IActionResult Delete(int id)
        {
            var teacher = context.Teachers.Find(id);
            if (teacher is null)
            {
                return NotFound();
            }
            FilesSettings.DeleteFile(teacher.ImageName, "images");

            var teacherM = mapper.Map<ShowTeachersVM>(teacher);
            return View(teacherM);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var teacher = context.Teachers.Find(id);
            if (teacher is null)
            {
                return RedirectToAction(nameof(Index));
            }

            context.Teachers.Remove(teacher);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

      
    }
}

E-Learning.PL/Controllers/ServicesController.cs
using AutoMapper;
using E_Learning.DAL.Data;
using Microsoft.AspNetCore.Mvc;

namespace E_Learning.PL.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IMapper mapper;

        public ServicesController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Learning.PL/Areas/Dashboard/Views/Teachers/Create.cshtml
@model TeacherFormVM


@section Header {
Teachers
}

<div class="col-md-9 m-auto w-50">

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Teacher</h3>
        </div>


        <form asp-controller="Teachers" asp-action="Create" enctype="multipart/form-data">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name">Teacher Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter Teacher Name">
                </div>
                <div class="form-group">
                    <label asp-for="Field">Teacher Field</label>
                    <input asp-for="Field" class="form-control" placeholder="Enter Teacher Field">
                </div>
                <div class="form-group">
                    <label asp-for="Phone">Teacher Phone</label>
                    <input asp-for="Phone" class="form-control" placeholder="Enter Teacher Phone">
                </div>
                <div class="form-group">
                    <label asp-for="Email">Teacher Email</label>
                    <input asp-for="Email" class="form-control" placeholder="Enter Teacher Email">
                </div>
                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control-file imageInput">
                </div>
                <div class="form-group">
                    <img src="#" id="imagePreview" style="display:none;width:200px" />
                </div>

                <div class="form-group">
                    <img src="#" id="imagePreview" style="display:none;width:200px" />
                </div>

            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

@section script {
    <script>
        document.querySelector(".imageInput").addEventListener("change", (event) => {
            const file=event.target.files[0];
            const imagePreview = document.querySelector("#imagePreview");
            if(file){
                const reader =new FileReader();
                reader.onload = function (e) {
                    console.log("hhhhhh");
                    imagePreview.src = e.target.result;
                    imagePreview.style.display = "block";
                }
                reader.readAsDataURL(file);
            }
        })
    </script>
}

E-Learning.PL/Areas/Dashboard/Views/Teachers/Delete.cshtml
@model ShowTeachersVM
@section Header {
    Delete Teacher...
}

<div class="col-md-9  m-auto w-50">

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title"> Delete @Model.Name </h3>
        </div>
        <div class="card-body">
            <h3 class="danger"> are you sure to delete the @Model.Name </h3>
        </div>

        <div class="card-footer">
            <form asp-controller="Teachers" asp-action="Delete" asp-route-id="@Model.Id">
<button type="Submit" class="btn btn-danger">Delete</button>
                <a asp-controller="Services" asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>


    </div>
</div>

E-Learning.PL/Areas/Dashboard/Views/Teachers/Details.cshtml
@model TeacherDetailsVM


@section Header{
    Teacher Details
}


<div class="col-md-9  m-auto w-50">

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">@Model.Name  Details</h3>
        </div>
        
        <ol class="list-group list-group-numbered">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Description</div>
                    <span class="badge text-bg-primary rounded-pill">@Model.Field</span>
                </div>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Description</div>
                    <span class="badge text-bg-primary rounded-pill">@Model.Phone</span>
                </div>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Description</div>
                    <span class="badge text-bg-primary rounded-pill">@Model.Email</span>
                </div>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Status</div>
                    <span class="badge text-bg-primary rounded-pill">@(@Model.StillWorked? "Deleted":"Active") </span>

                </div>
            </li>
            <li class="list-group-item d-flex justify-content-start align-items-start">
                Image: <img class="w-25" src="~/files/images/@Model.ImageName" />
            </li>
           
        </ol>

    </div>
</div>

E-Learning.PL/Areas/Dashboard/Views/Teachers/Edit.cshtml
@model TeacherFormVM


@section Header {
Edit Teachers ...
}

<div class="col-md-9  m-auto w-50">

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit Teacher</h3>
        </div>


        <form asp-controller="Teachers" asp-action="Edit" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="Name">Teacher Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Enter Teacher Name">
                </div>
                <div class="form-group">
                    <label asp-for="Field">Teacher Field</label>
                    <input asp-for="Field" class="form-control" placeholder="Enter Teacher Field">
                </div>
                <div class="form-group">
                    <label asp-for="Phone">Teacher Phone</label>
                    <input asp-for="Phone" class="form-control" placeholder="Enter Teacher Phone">
                </div>
                <div class="form-group">
                    <label asp-for="Email">Teacher Email</label>
                    <input asp-for="Email" class="form-control" placeholder="Enter Teacher Email">
                </div>
                 <div class="form-group">
                     <label asp-for="StillWorked"></label>
                     <input asp-for="StillWorked">
                     <span>@(Model.StillWorked ? " Yes" : "No")</span>
                 </div>

                <div class="form-group">
                    <label asp-for="Image"></label>
                    <input asp-for="Image" class="form-control-file imageInput">
                </div>
                <div class="form-group">
                    <img src="#" id="imagePreview" style="display:none;width:200px" />
                </div>


            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
@section script {
    <script>
        document.querySelector(".imageInput").addEventListener("change", (event) => {
            const file = event.target.files[0];
            const imagePreview = document.querySelector("#imagePreview");
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    console.log("hhhhhh");
                    imagePreview.src = e.target.result;
                    imagePreview.style.display = "block";
                }
                reader.readAsDataURL(file);
            }
        })
    </script>
}

E-Learning.PL/Areas/Dashboard/Views/Teachers/Index.cshtml
@model IEnumerable<ShowTeachersVM>

@section Header {
    Our Teachers
}
@section style {
    <link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.min.css" rel="stylesheet" />

}

<div class="col-md-9  m-auto w-50">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Our Teachers Table</h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Working Status</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.StillWorked</td>
                            <td>
                                <a asp-controller="Teachers" asp-action="Edit" asp-route-id="@item.Id" class="btn bg-gradient-secondary btn-m">Edit</a>
                                <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.Id" class="btn bg-gradient-warning btn-m">Details</a>
                                <a asp-controller="Teachers" asp-action="Delete" asp-route-id="@item.Id" class="btn bg-gradient-danger btn-m">Delete</a>
                            </td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>

        <div class="card-footer clearfix">
            <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">«</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">»</a></li>
            </ul>
        </div>
    </div>


</div>
@section script {
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" integrity="sha512-XMVd28F1oH/O71fzwBnV7HucLxVwtxf26XV8P4wPk26EDxuGZ91N8bsOttmnomcCD3CS5ZMRL50H0GgOHvegtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/pdfmake.min.js" integrity="sha512-axXaF5grZBaYl7qiM6OMHgsgVXdSLxqq0w7F4CQxuFyrcPmn0JfnqsOtYHUun80g6mRRdvJDrTCyL8LQqBOt/Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.12/vfs_fonts.min.js" integrity="sha512-EFlschXPq/G5zunGPRSYqazR1CMKj0cQc8v6eMrQwybxgIbhsfoO5NAMQX3xFDQIbFlViv53o7Hy+yCWw6iZxA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.print.min.js"></script>


    <script>
        new DataTable('table', {
            layout: {
                topStart: {
                    buttons: [
                        'copy', 'excel', 'pdf'
                    ]
                }
            }
        });</script>
}